/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '../../client'
import type { RequestConfig, ResponseErrorConfig } from '../../client'
import type { GetCartByIdQueryResponse, GetCartByIdPathParams, GetCartById400 } from '../../types/GetCartById'
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from '@tanstack/react-query'
import { queryOptions, useQuery } from '@tanstack/react-query'

export const getCartByIdQueryKey = (id: GetCartByIdPathParams['id']) => [{ url: '/carts/:id', params: { id: id } }] as const

export type GetCartByIdQueryKey = ReturnType<typeof getCartByIdQueryKey>

/**
 * @description Retrieve details of a specific cart by ID.
 * @summary Get a single cart
 * {@link /carts/:id}
 */
export async function getCartById(id: GetCartByIdPathParams['id'], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config

  const res = await request<GetCartByIdQueryResponse, ResponseErrorConfig<GetCartById400>, unknown>({ method: 'GET', url: `/carts/${id}`, ...requestConfig })
  return res.data
}

export function getCartByIdQueryOptions(id: GetCartByIdPathParams['id'], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getCartByIdQueryKey(id)
  return queryOptions<GetCartByIdQueryResponse, ResponseErrorConfig<GetCartById400>, GetCartByIdQueryResponse, typeof queryKey>({
    enabled: !!id,
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return getCartById(id, config)
    },
  })
}

/**
 * @description Retrieve details of a specific cart by ID.
 * @summary Get a single cart
 * {@link /carts/:id}
 */
export function useGetCartById<TData = GetCartByIdQueryResponse, TQueryData = GetCartByIdQueryResponse, TQueryKey extends QueryKey = GetCartByIdQueryKey>(
  id: GetCartByIdPathParams['id'],
  options: {
    query?: Partial<QueryObserverOptions<GetCartByIdQueryResponse, ResponseErrorConfig<GetCartById400>, TData, TQueryData, TQueryKey>> & {
      client?: QueryClient
    }
    client?: Partial<RequestConfig> & { client?: typeof fetch }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? getCartByIdQueryKey(id)

  const query = useQuery(
    {
      ...getCartByIdQueryOptions(id, config),
      queryKey,
      ...queryOptions,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<GetCartById400>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}