/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '../../client'
import type { RequestConfig, ResponseErrorConfig } from '../../client'
import type { LoginUserMutationRequest, LoginUserMutationResponse, LoginUser400 } from '../../types/LoginUser'
import type { UseMutationOptions, QueryClient } from '@tanstack/react-query'
import { useMutation } from '@tanstack/react-query'

export const loginUserMutationKey = () => [{ url: '/auth/login' }] as const

export type LoginUserMutationKey = ReturnType<typeof loginUserMutationKey>

/**
 * @description Authenticate a user.
 * @summary Login
 * {@link /auth/login}
 */
export async function loginUser(data?: LoginUserMutationRequest, config: Partial<RequestConfig<LoginUserMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config

  const requestData = data
  const res = await request<LoginUserMutationResponse, ResponseErrorConfig<LoginUser400>, LoginUserMutationRequest>({
    method: 'POST',
    url: `/auth/login`,
    data: requestData,
    ...requestConfig,
  })
  return res.data
}

/**
 * @description Authenticate a user.
 * @summary Login
 * {@link /auth/login}
 */
export function useLoginUser<TContext>(
  options: {
    mutation?: UseMutationOptions<LoginUserMutationResponse, ResponseErrorConfig<LoginUser400>, { data?: LoginUserMutationRequest }, TContext> & {
      client?: QueryClient
    }
    client?: Partial<RequestConfig<LoginUserMutationRequest>> & { client?: typeof fetch }
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation
  const mutationKey = mutationOptions.mutationKey ?? loginUserMutationKey()

  return useMutation<LoginUserMutationResponse, ResponseErrorConfig<LoginUser400>, { data?: LoginUserMutationRequest }, TContext>(
    {
      mutationFn: async ({ data }) => {
        return loginUser(data, config)
      },
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  )
}