/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '../../client'
import type { RequestConfig, ResponseErrorConfig } from '../../client'
import type { GetProductByIdQueryResponse, GetProductByIdPathParams, GetProductById400 } from '../../types/GetProductById'
import type { InfiniteData, QueryKey, QueryClient, InfiniteQueryObserverOptions, UseInfiniteQueryResult } from '@tanstack/react-query'
import { infiniteQueryOptions, useInfiniteQuery } from '@tanstack/react-query'

export const getProductByIdInfiniteQueryKey = (id: GetProductByIdPathParams['id']) => [{ url: '/products/:id', params: { id: id } }] as const

export type GetProductByIdInfiniteQueryKey = ReturnType<typeof getProductByIdInfiniteQueryKey>

/**
 * @description Retrieve details of a specific product by ID.
 * @summary Get a single product
 * {@link /products/:id}
 */
export async function getProductByIdInfinite(id: GetProductByIdPathParams['id'], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config

  const res = await request<GetProductByIdQueryResponse, ResponseErrorConfig<GetProductById400>, unknown>({
    method: 'GET',
    url: `/products/${id}`,
    ...requestConfig,
  })
  return res.data
}

export function getProductByIdInfiniteQueryOptions(id: GetProductByIdPathParams['id'], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getProductByIdInfiniteQueryKey(id)
  return infiniteQueryOptions<GetProductByIdQueryResponse, ResponseErrorConfig<GetProductById400>, GetProductByIdQueryResponse, typeof queryKey>({
    enabled: !!id,
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return getProductByIdInfinite(id, config)
    },
    initialPageParam: 0,
    getNextPageParam: (lastPage) => lastPage['nextCursor'],
    getPreviousPageParam: (firstPage) => firstPage['nextCursor'],
  })
}

/**
 * @description Retrieve details of a specific product by ID.
 * @summary Get a single product
 * {@link /products/:id}
 */
export function useGetProductByIdInfinite<
  TData = InfiniteData<GetProductByIdQueryResponse>,
  TQueryData = GetProductByIdQueryResponse,
  TQueryKey extends QueryKey = GetProductByIdInfiniteQueryKey,
>(
  id: GetProductByIdPathParams['id'],
  options: {
    query?: Partial<InfiniteQueryObserverOptions<GetProductByIdQueryResponse, ResponseErrorConfig<GetProductById400>, TData, TQueryKey>> & {
      client?: QueryClient
    }
    client?: Partial<RequestConfig> & { client?: typeof fetch }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? getProductByIdInfiniteQueryKey(id)

  const query = useInfiniteQuery(
    {
      ...getProductByIdInfiniteQueryOptions(id, config),
      queryKey,
      ...queryOptions,
    } as unknown as InfiniteQueryObserverOptions,
    queryClient,
  ) as UseInfiniteQueryResult<TData, ResponseErrorConfig<GetProductById400>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}