/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '../../client'
import type { RequestConfig, ResponseErrorConfig } from '../../client'
import type { GetProductByIdQueryResponse, GetProductByIdPathParams, GetProductById400 } from '../../types/GetProductById'
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from '@tanstack/react-query'
import { queryOptions, useSuspenseQuery } from '@tanstack/react-query'

export const getProductByIdSuspenseQueryKey = (id: GetProductByIdPathParams['id']) => [{ url: '/products/:id', params: { id: id } }] as const

export type GetProductByIdSuspenseQueryKey = ReturnType<typeof getProductByIdSuspenseQueryKey>

/**
 * @description Retrieve details of a specific product by ID.
 * @summary Get a single product
 * {@link /products/:id}
 */
export async function getProductByIdSuspense(id: GetProductByIdPathParams['id'], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config

  const res = await request<GetProductByIdQueryResponse, ResponseErrorConfig<GetProductById400>, unknown>({
    method: 'GET',
    url: `/products/${id}`,
    ...requestConfig,
  })
  return res.data
}

export function getProductByIdSuspenseQueryOptions(id: GetProductByIdPathParams['id'], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getProductByIdSuspenseQueryKey(id)
  return queryOptions<GetProductByIdQueryResponse, ResponseErrorConfig<GetProductById400>, GetProductByIdQueryResponse, typeof queryKey>({
    enabled: !!id,
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return getProductByIdSuspense(id, config)
    },
  })
}

/**
 * @description Retrieve details of a specific product by ID.
 * @summary Get a single product
 * {@link /products/:id}
 */
export function useGetProductByIdSuspense<TData = GetProductByIdQueryResponse, TQueryKey extends QueryKey = GetProductByIdSuspenseQueryKey>(
  id: GetProductByIdPathParams['id'],
  options: {
    query?: Partial<UseSuspenseQueryOptions<GetProductByIdQueryResponse, ResponseErrorConfig<GetProductById400>, TData, TQueryKey>> & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: typeof fetch }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? getProductByIdSuspenseQueryKey(id)

  const query = useSuspenseQuery(
    {
      ...getProductByIdSuspenseQueryOptions(id, config),
      queryKey,
      ...queryOptions,
    } as unknown as UseSuspenseQueryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<GetProductById400>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}