/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '../../client'
import type { RequestConfig, ResponseErrorConfig } from '../../client'
import type { AddUserMutationRequest, AddUserMutationResponse, AddUser400 } from '../../types/AddUser'
import type { UseMutationOptions, QueryClient } from '@tanstack/react-query'
import { useMutation } from '@tanstack/react-query'

export const addUserMutationKey = () => [{ url: '/users' }] as const

export type AddUserMutationKey = ReturnType<typeof addUserMutationKey>

/**
 * @description Create a new user.
 * @summary Add a new user
 * {@link /users}
 */
export async function addUser(data?: AddUserMutationRequest, config: Partial<RequestConfig<AddUserMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config

  const requestData = data
  const res = await request<AddUserMutationResponse, ResponseErrorConfig<AddUser400>, AddUserMutationRequest>({
    method: 'POST',
    url: `/users`,
    data: requestData,
    ...requestConfig,
  })
  return res.data
}

/**
 * @description Create a new user.
 * @summary Add a new user
 * {@link /users}
 */
export function useAddUser<TContext>(
  options: {
    mutation?: UseMutationOptions<AddUserMutationResponse, ResponseErrorConfig<AddUser400>, { data?: AddUserMutationRequest }, TContext> & {
      client?: QueryClient
    }
    client?: Partial<RequestConfig<AddUserMutationRequest>> & { client?: typeof fetch }
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation
  const mutationKey = mutationOptions.mutationKey ?? addUserMutationKey()

  return useMutation<AddUserMutationResponse, ResponseErrorConfig<AddUser400>, { data?: AddUserMutationRequest }, TContext>(
    {
      mutationFn: async ({ data }) => {
        return addUser(data, config)
      },
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  )
}