/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '../../client'
import type { RequestConfig, ResponseErrorConfig } from '../../client'
import type { GetUserByIdQueryResponse, GetUserByIdPathParams, GetUserById400 } from '../../types/GetUserById'
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from '@tanstack/react-query'
import { queryOptions, useSuspenseQuery } from '@tanstack/react-query'

export const getUserByIdSuspenseQueryKey = (id: GetUserByIdPathParams['id']) => [{ url: '/users/:id', params: { id: id } }] as const

export type GetUserByIdSuspenseQueryKey = ReturnType<typeof getUserByIdSuspenseQueryKey>

/**
 * @description Retrieve details of a specific user by ID.
 * @summary Get a single user
 * {@link /users/:id}
 */
export async function getUserByIdSuspense(id: GetUserByIdPathParams['id'], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config

  const res = await request<GetUserByIdQueryResponse, ResponseErrorConfig<GetUserById400>, unknown>({ method: 'GET', url: `/users/${id}`, ...requestConfig })
  return res.data
}

export function getUserByIdSuspenseQueryOptions(id: GetUserByIdPathParams['id'], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getUserByIdSuspenseQueryKey(id)
  return queryOptions<GetUserByIdQueryResponse, ResponseErrorConfig<GetUserById400>, GetUserByIdQueryResponse, typeof queryKey>({
    enabled: !!id,
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return getUserByIdSuspense(id, config)
    },
  })
}

/**
 * @description Retrieve details of a specific user by ID.
 * @summary Get a single user
 * {@link /users/:id}
 */
export function useGetUserByIdSuspense<TData = GetUserByIdQueryResponse, TQueryKey extends QueryKey = GetUserByIdSuspenseQueryKey>(
  id: GetUserByIdPathParams['id'],
  options: {
    query?: Partial<UseSuspenseQueryOptions<GetUserByIdQueryResponse, ResponseErrorConfig<GetUserById400>, TData, TQueryKey>> & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: typeof fetch }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? getUserByIdSuspenseQueryKey(id)

  const query = useSuspenseQuery(
    {
      ...getUserByIdSuspenseQueryOptions(id, config),
      queryKey,
      ...queryOptions,
    } as unknown as UseSuspenseQueryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<GetUserById400>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}