/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '../../client'
import type { RequestConfig, ResponseErrorConfig } from '../../client'
import type { GetAllUsersQueryResponse, GetAllUsers400 } from '../../types/GetAllUsers'
import type { InfiniteData, QueryKey, QueryClient, InfiniteQueryObserverOptions, UseInfiniteQueryResult } from '@tanstack/react-query'
import { infiniteQueryOptions, useInfiniteQuery } from '@tanstack/react-query'

export const getAllUsersInfiniteQueryKey = () => [{ url: '/users' }] as const

export type GetAllUsersInfiniteQueryKey = ReturnType<typeof getAllUsersInfiniteQueryKey>

/**
 * @description Retrieve a list of all users.
 * @summary Get all users
 * {@link /users}
 */
export async function getAllUsersInfinite(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config

  const res = await request<GetAllUsersQueryResponse, ResponseErrorConfig<GetAllUsers400>, unknown>({ method: 'GET', url: `/users`, ...requestConfig })
  return res.data
}

export function getAllUsersInfiniteQueryOptions(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getAllUsersInfiniteQueryKey()
  return infiniteQueryOptions<GetAllUsersQueryResponse, ResponseErrorConfig<GetAllUsers400>, GetAllUsersQueryResponse, typeof queryKey>({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return getAllUsersInfinite(config)
    },
    initialPageParam: 0,
    getNextPageParam: (lastPage) => lastPage['nextCursor'],
    getPreviousPageParam: (firstPage) => firstPage['nextCursor'],
  })
}

/**
 * @description Retrieve a list of all users.
 * @summary Get all users
 * {@link /users}
 */
export function useGetAllUsersInfinite<
  TData = InfiniteData<GetAllUsersQueryResponse>,
  TQueryData = GetAllUsersQueryResponse,
  TQueryKey extends QueryKey = GetAllUsersInfiniteQueryKey,
>(
  options: {
    query?: Partial<InfiniteQueryObserverOptions<GetAllUsersQueryResponse, ResponseErrorConfig<GetAllUsers400>, TData, TQueryKey>> & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: typeof fetch }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? getAllUsersInfiniteQueryKey()

  const query = useInfiniteQuery(
    {
      ...getAllUsersInfiniteQueryOptions(config),
      queryKey,
      ...queryOptions,
    } as unknown as InfiniteQueryObserverOptions,
    queryClient,
  ) as UseInfiniteQueryResult<TData, ResponseErrorConfig<GetAllUsers400>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}