/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '../../client'
import type { RequestConfig, ResponseErrorConfig } from '../../client'
import type { GetAllUsersQueryResponse, GetAllUsers400 } from '../../types/GetAllUsers'
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from '@tanstack/react-query'
import { queryOptions, useSuspenseQuery } from '@tanstack/react-query'

export const getAllUsersSuspenseQueryKey = () => [{ url: '/users' }] as const

export type GetAllUsersSuspenseQueryKey = ReturnType<typeof getAllUsersSuspenseQueryKey>

/**
 * @description Retrieve a list of all users.
 * @summary Get all users
 * {@link /users}
 */
export async function getAllUsersSuspense(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config

  const res = await request<GetAllUsersQueryResponse, ResponseErrorConfig<GetAllUsers400>, unknown>({ method: 'GET', url: `/users`, ...requestConfig })
  return res.data
}

export function getAllUsersSuspenseQueryOptions(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getAllUsersSuspenseQueryKey()
  return queryOptions<GetAllUsersQueryResponse, ResponseErrorConfig<GetAllUsers400>, GetAllUsersQueryResponse, typeof queryKey>({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return getAllUsersSuspense(config)
    },
  })
}

/**
 * @description Retrieve a list of all users.
 * @summary Get all users
 * {@link /users}
 */
export function useGetAllUsersSuspense<TData = GetAllUsersQueryResponse, TQueryKey extends QueryKey = GetAllUsersSuspenseQueryKey>(
  options: {
    query?: Partial<UseSuspenseQueryOptions<GetAllUsersQueryResponse, ResponseErrorConfig<GetAllUsers400>, TData, TQueryKey>> & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: typeof fetch }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? getAllUsersSuspenseQueryKey()

  const query = useSuspenseQuery(
    {
      ...getAllUsersSuspenseQueryOptions(config),
      queryKey,
      ...queryOptions,
    } as unknown as UseSuspenseQueryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<GetAllUsers400>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}