/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '../../client'
import type { RequestConfig, ResponseErrorConfig } from '../../client'
import type { GetAllUsersQueryResponse, GetAllUsers400 } from '../../types/GetAllUsers'
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from '@tanstack/react-query'
import { queryOptions, useQuery } from '@tanstack/react-query'

export const getAllUsersQueryKey = () => [{ url: '/users' }] as const

export type GetAllUsersQueryKey = ReturnType<typeof getAllUsersQueryKey>

/**
 * @description Retrieve a list of all users.
 * @summary Get all users
 * {@link /users}
 */
export async function getAllUsers(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config

  const res = await request<GetAllUsersQueryResponse, ResponseErrorConfig<GetAllUsers400>, unknown>({ method: 'GET', url: `/users`, ...requestConfig })
  return res.data
}

export function getAllUsersQueryOptions(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getAllUsersQueryKey()
  return queryOptions<GetAllUsersQueryResponse, ResponseErrorConfig<GetAllUsers400>, GetAllUsersQueryResponse, typeof queryKey>({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return getAllUsers(config)
    },
  })
}

/**
 * @description Retrieve a list of all users.
 * @summary Get all users
 * {@link /users}
 */
export function useGetAllUsers<TData = GetAllUsersQueryResponse, TQueryData = GetAllUsersQueryResponse, TQueryKey extends QueryKey = GetAllUsersQueryKey>(
  options: {
    query?: Partial<QueryObserverOptions<GetAllUsersQueryResponse, ResponseErrorConfig<GetAllUsers400>, TData, TQueryData, TQueryKey>> & {
      client?: QueryClient
    }
    client?: Partial<RequestConfig> & { client?: typeof fetch }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? getAllUsersQueryKey()

  const query = useQuery(
    {
      ...getAllUsersQueryOptions(config),
      queryKey,
      ...queryOptions,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<GetAllUsers400>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}