/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Product } from './Product'

/**
 * @description Product created successfully
 */
export type AddProduct201 = Product

/**
 * @description Bad request
 */
export type AddProduct400 = any

export type AddProductMutationRequest = Product

export type AddProductMutationResponse = AddProduct201

export type AddProductMutation = {
  Response: AddProduct201
  Request: AddProductMutationRequest
  Errors: AddProduct400
}