/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { User } from './User'

/**
 * @description User created successfully
 */
export type AddUser201 = User

/**
 * @description Bad request
 */
export type AddUser400 = any

export type AddUserMutationRequest = User

export type AddUserMutationResponse = AddUser201

export type AddUserMutation = {
  Response: AddUser201
  Request: AddUserMutationRequest
  Errors: AddUser400
}