/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Product } from './Product'

export type Cart = {
  /**
   * @type integer | undefined
   */
  id?: number
  /**
   * @type integer | undefined
   */
  userId?: number
  /**
   * @type array | undefined
   */
  products?: Product[]
}