/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type DeleteCartPathParams = {
  /**
   * @type integer
   */
  id: number
}

/**
 * @description Cart deleted successfully
 */
export type DeleteCart200 = any

/**
 * @description Bad request
 */
export type DeleteCart400 = any

export type DeleteCartMutationResponse = DeleteCart200

export type DeleteCartMutation = {
  Response: DeleteCart200
  PathParams: DeleteCartPathParams
  Errors: DeleteCart400
}