/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type DeleteProductPathParams = {
  /**
   * @type integer
   */
  id: number
}

/**
 * @description Product deleted successfully
 */
export type DeleteProduct200 = any

/**
 * @description Bad request
 */
export type DeleteProduct400 = any

export type DeleteProductMutationResponse = DeleteProduct200

export type DeleteProductMutation = {
  Response: DeleteProduct200
  PathParams: DeleteProductPathParams
  Errors: DeleteProduct400
}