/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type DeleteUserPathParams = {
  /**
   * @type integer
   */
  id: number
}

/**
 * @description User deleted successfully
 */
export type DeleteUser200 = any

/**
 * @description Bad request
 */
export type DeleteUser400 = any

export type DeleteUserMutationResponse = DeleteUser200

export type DeleteUserMutation = {
  Response: DeleteUser200
  PathParams: DeleteUserPathParams
  Errors: DeleteUser400
}