/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Product } from './Product'

/**
 * @description Success
 */
export type GetAllProducts200 = Product[]

/**
 * @description Bad request
 */
export type GetAllProducts400 = any

export type GetAllProductsQueryResponse = GetAllProducts200

export type GetAllProductsQuery = {
  Response: GetAllProducts200
  Errors: GetAllProducts400
}