/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { User } from './User'

/**
 * @description Success
 */
export type GetAllUsers200 = User[]

/**
 * @description Bad request
 */
export type GetAllUsers400 = any

export type GetAllUsersQueryResponse = GetAllUsers200

export type GetAllUsersQuery = {
  Response: GetAllUsers200
  Errors: GetAllUsers400
}