/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Cart } from './Cart'

/**
 * @description Success
 */
export type GetAllCarts200 = Cart[]

/**
 * @description Bad request
 */
export type GetAllCarts400 = any

export type GetAllCartsQueryResponse = GetAllCarts200

export type GetAllCartsQuery = {
  Response: GetAllCarts200
  Errors: GetAllCarts400
}