/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Cart } from './Cart'

export type GetCartByIdPathParams = {
  /**
   * @type integer
   */
  id: number
}

/**
 * @description Success
 */
export type GetCartById200 = Cart

/**
 * @description Bad request
 */
export type GetCartById400 = any

export type GetCartByIdQueryResponse = GetCartById200

export type GetCartByIdQuery = {
  Response: GetCartById200
  PathParams: GetCartByIdPathParams
  Errors: GetCartById400
}