/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Product } from './Product'

export type GetProductByIdPathParams = {
  /**
   * @type integer
   */
  id: number
}

/**
 * @description Success
 */
export type GetProductById200 = Product

/**
 * @description Bad request
 */
export type GetProductById400 = any

export type GetProductByIdQueryResponse = GetProductById200

export type GetProductByIdQuery = {
  Response: GetProductById200
  PathParams: GetProductByIdPathParams
  Errors: GetProductById400
}