/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { User } from './User'

export type GetUserByIdPathParams = {
  /**
   * @type integer
   */
  id: number
}

/**
 * @description Success
 */
export type GetUserById200 = User

/**
 * @description Bad request
 */
export type GetUserById400 = any

export type GetUserByIdQueryResponse = GetUserById200

export type GetUserByIdQuery = {
  Response: GetUserById200
  PathParams: GetUserByIdPathParams
  Errors: GetUserById400
}