/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Login } from './Login'
import type { LoginResponse } from './LoginResponse'

/**
 * @description Login successful
 */
export type LoginUser200 = LoginResponse

/**
 * @description Bad request
 */
export type LoginUser400 = any

export type LoginUserMutationRequest = Login

export type LoginUserMutationResponse = LoginUser200

export type LoginUserMutation = {
  Response: LoginUser200
  Request: LoginUserMutationRequest
  Errors: LoginUser400
}