/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type Product = {
  /**
   * @type integer | undefined
   */
  id?: number
  /**
   * @type string | undefined
   */
  title?: string
  /**
   * @type number | undefined, float
   */
  price?: number
  /**
   * @type string | undefined
   */
  description?: string
  /**
   * @type string | undefined
   */
  category?: string
  /**
   * @type string | undefined, uri
   */
  image?: string
}