/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Product } from './Product'

export type UpdateProductPathParams = {
  /**
   * @type integer
   */
  id: number
}

/**
 * @description Product updated successfully
 */
export type UpdateProduct200 = Product

/**
 * @description Bad request
 */
export type UpdateProduct400 = any

export type UpdateProductMutationRequest = Product

export type UpdateProductMutationResponse = UpdateProduct200

export type UpdateProductMutation = {
  Response: UpdateProduct200
  Request: UpdateProductMutationRequest
  PathParams: UpdateProductPathParams
  Errors: UpdateProduct400
}