/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Cart } from './Cart'

export type UpdateCartPathParams = {
  /**
   * @type integer
   */
  id: number
}

/**
 * @description Cart updated successfully
 */
export type UpdateCart200 = Cart

/**
 * @description Bad request
 */
export type UpdateCart400 = any

export type UpdateCartMutationRequest = Cart

export type UpdateCartMutationResponse = UpdateCart200

export type UpdateCartMutation = {
  Response: UpdateCart200
  Request: UpdateCartMutationRequest
  PathParams: UpdateCartPathParams
  Errors: UpdateCart400
}