/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type User = {
  /**
   * @type integer | undefined
   */
  id?: number
  /**
   * @type string | undefined
   */
  username?: string
  /**
   * @type string | undefined
   */
  email?: string
  /**
   * @type string | undefined
   */
  password?: string
}